### ISSUE TITLE
Subdivision of Peer Struct

### ISSUE THREAD

**Issue by tdahar** [migalabs/armiarma#31]
After reviewing the Peer struct it may be possible to subdivide the Peer struct into smaller structs in order to organize code better and make it easier to read it. We could build different packages like Host, Connections, Messages... This way we could divide corresponding methods into the different structs.
Please let me know what you think about it :)

Maybe this could be a good division?
![image](https://user-images.githubusercontent.com/18716811/139406184-15225e8c-5579-4cd0-aee9-6d806550efc7.png)

**Comment by cortze** [comment]
closing this, as it is solved in #52 -> even though the new version only supports the ethereum cl network, the crawler is modular enough to make it compatible with other networks
