### ISSUE TITLE
Modification of agent version for Lodestar

### ISSUE THREAD

**Issue by philknows** [migalabs/armiarma#49]
Reference: https://github.com/ChainSafe/lodestar/issues/4465

Lodestar is looking to modify the agent version gossiped from the default libp2p string `js-libp2p/0.36.2` to `lodestar/version`. We are requesting an update to your crawler on how you identify Lodestar nodes for better tracking and referencing of Lodestar peers on the network for debug/stats purposes.

**Comment by cortze** [comment]
Hey @philknows thanks for letting us know about the change! I'm afk until Monday, but will take care of it 😁

**Comment by cortze** [comment]
Hey @philknows , I also discovered that Grandine also upgraded from `rust-libp2p/{version}` to `Grandine-{version}`. 
Updating them both in this [commit](https://github.com/migalabs/armiarma/pull/50/commits/cb170b68b6a058bf24642e40db0fdb4960e63db3)

**Comment by cortze** [comment]
Closed with #50
